---
- name: enable docker
  include_role:
    name: docker

- name: create /mnt/media
  file:
    state: directory
    path: /mnt/media

- name: install web server
  include_role: 
    name: gateway-server

- name: enable plex reverse proxy
  copy:
    src: media.akdev.conf
    dest: /etc/httpd/conf.d

- name: deploy docker-plex.service
  copy:
    src: docker-plex.service
    dest: /etc/systemd/system

- name: systemd daemon reload
  systemd:
    daemon_reload: true

# tasks file for plex
