---
- name: install apache
  dnf:
    name: httpd
    state: latest

- name: add httpd port to firewall
  firewalld:
    service: http
    state: enabled
  
- name: enable service
  systemd:
    name: httpd
    state: started
# tasks file for apache-server
